name: tally_connector
description: "Tally ERP Data Connector App"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter

  amazon_cognito_identity_dart_2: ^3.6.4
  
  # UI
  cupertino_icons: ^1.0.8
  
  # HTTP & API
  http: ^1.2.0
  
  # Secure Storage
  flutter_secure_storage: ^9.0.0
  
  # Form Validation
  email_validator: ^2.1.17
  sqflite_common_ffi: ^2.4.0+1
  sqflite: ^2.4.2
  sqlite3: ^3.1.2
  sqlite3_flutter_libs: ^0.5.24
  xml: ^6.6.1
  postgres: ^3.5.9
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  printing: ^5.12.0
  pdf: ^3.10.8
  flutter_svg: ^2.0.10+1
  image_picker: ^1.0.7
  screenshot: ^3.0.0
  share_plus: ^7.2.2
  fl_chart: ^1.2.0

  # Local Push Notifications (scheduled & immediate)
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  # Windows desktop notifications
  local_notifier: ^0.1.6

  # Utilities
  path: ^1.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true